# Generated by Django 4.2.8 on 2024-02-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='project',
            name='codelink',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img',
        ),
        migrations.RemoveField(
            model_name='project',
            name='publish_date',
        ),
    ]
