# Generated by Django 4.2.8 on 2024-02-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fulltext',
            field=models.URLField(blank=True),
        ),
    ]
