# Generated by Django 4.2.8 on 2024-02-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_fulltext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abstract',
            field=models.TextField(blank=True),
        ),
    ]
