# Generated by Django 4.2.8 on 2024-02-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_project_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.PositiveBigIntegerField(default=4),
            preserve_default=False,
        ),
    ]
