# Generated by Django 4.2.8 on 2024-02-09 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_project_publish_date_project_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fulltext',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img',
        ),
    ]
