# Generated by Django 4.2.8 on 2024-02-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_project_year_project_fulltext_project_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
