# Generated by Django 4.2.8 on 2024-02-09 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_project_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 4, 25, 42, 131022, tzinfo=datetime.timezone.utc)),
        ),
    ]
